name: applications
root: "~/Repos/github.com/tittitoo/applications/"

windows:
  - applications:
      root:
      panes:
  - applications:
      root:
      panes:
  - playground:
      root:
      panes:
