[ids]
1c4f:007f:5bcae51d

[global]
overload_tap_timeout = 200

[main]
esc = tab
tab = esc
capslock = leftcontrol
leftcontrol = capslock

a = lettermod(shift, a, 150, 200)
s = lettermod(alt, s, 150, 200)
d = lettermod(meta, d, 150, 200)
f = lettermod(control, f, 150, 200)

j = lettermod(control, j, 150, 200)
k = lettermod(meta, k, 150, 200)
l = lettermod(alt, l, 150, 200)
semicolon = lettermod(shift, semicolon, 150, 200)
